$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
    samples:
          type: string
    adapters:
          type: string
    threads:
          type: integer
    phix:
          type: string
    reduced_tree:
          type: boolean
    bakta_db:
          type: string
    mdmcleaner_db:
          type: string

required:
  - samples
  - adapters
  - phix
  - bakta_db
  - mdmcleaner_db
